"""Corpus snapshot pinning, hidden holdout and prior-art boundaries (K05).

The records here pin, partition and bound evidence; they never score, promote
or read a clock, and the holdout manifest itself is written by the Verifier
Firewall rather than restated.
"""

from __future__ import annotations

from .boundaries import (
    ASSESSMENT_ID_PREFIX,
    BOUNDARY_ID_PREFIX,
    CORPUS_BOUNDED_POSITION,
    DOCUMENT_FIELDS,
    FINDING_CODES,
    HANDLE_DIGEST_LENGTH,
    HANDLE_ID_PREFIX,
    HOLDOUT_ID_PREFIX,
    INTEGRITY_FAIL_POSITION,
    INTEGRITY_NOT_RUN_POSITION,
    INTEGRITY_PASS_POSITION,
    NOVELTY_LADDER,
    NOVELTY_SCHEMA,
    NOVELTY_STATUS_POSITION,
    PARTITION_ID_PREFIX,
    PRIOR_ART_FOUND_POSITION,
    PROMOTION_CEILING_POSITION,
    REPORT_ID_PREFIX,
    SEARCH_BOUNDED_POSITION,
    SNAPSHOT_ID_PREFIX,
    UNDECLARED_LICENSE_POSITION,
    CorpusBoundaryError,
    assess_novelty_within_boundary,
    build_snapshot_integrity_reports,
    declare_prior_art_boundary,
    holdout_handle,
    integrity_check_vocabulary,
    integrity_overall_vocabulary,
    license_vocabulary,
    novelty_dimension_vocabulary,
    partition_pinned_snapshot,
    pin_corpus_snapshot,
    pinned_documents,
    report_id_for,
    require_boundary_identity,
    require_holdout_drawn_from_snapshot,
    require_partition_identity,
    require_snapshot_identity,
    revalidate_corpus_snapshot,
    scalar_enum_field,
    seal_holdout_boundary,
    snapshot_id_for,
)

__all__ = [
    "ASSESSMENT_ID_PREFIX",
    "BOUNDARY_ID_PREFIX",
    "CORPUS_BOUNDED_POSITION",
    "DOCUMENT_FIELDS",
    "FINDING_CODES",
    "HANDLE_DIGEST_LENGTH",
    "HANDLE_ID_PREFIX",
    "HOLDOUT_ID_PREFIX",
    "INTEGRITY_FAIL_POSITION",
    "INTEGRITY_NOT_RUN_POSITION",
    "INTEGRITY_PASS_POSITION",
    "NOVELTY_LADDER",
    "NOVELTY_SCHEMA",
    "NOVELTY_STATUS_POSITION",
    "PARTITION_ID_PREFIX",
    "PRIOR_ART_FOUND_POSITION",
    "PROMOTION_CEILING_POSITION",
    "REPORT_ID_PREFIX",
    "SEARCH_BOUNDED_POSITION",
    "SNAPSHOT_ID_PREFIX",
    "UNDECLARED_LICENSE_POSITION",
    "CorpusBoundaryError",
    "assess_novelty_within_boundary",
    "build_snapshot_integrity_reports",
    "declare_prior_art_boundary",
    "holdout_handle",
    "integrity_check_vocabulary",
    "integrity_overall_vocabulary",
    "license_vocabulary",
    "novelty_dimension_vocabulary",
    "partition_pinned_snapshot",
    "pin_corpus_snapshot",
    "pinned_documents",
    "report_id_for",
    "require_boundary_identity",
    "require_holdout_drawn_from_snapshot",
    "require_partition_identity",
    "require_snapshot_identity",
    "revalidate_corpus_snapshot",
    "scalar_enum_field",
    "seal_holdout_boundary",
    "snapshot_id_for",
]
