"""Typed fail-closed errors for the K01 document-registration boundary."""

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, NoReturn


DOCUMENT_CONTRACT_INVALID = "DOCUMENT_CONTRACT_INVALID"
DOCUMENT_REQUEST_HASH_MISMATCH = "DOCUMENT_REQUEST_HASH_MISMATCH"
DOCUMENT_REQUEST_ID_MISMATCH = "DOCUMENT_REQUEST_ID_MISMATCH"
DOCUMENT_REGISTRATION_HASH_MISMATCH = "DOCUMENT_REGISTRATION_HASH_MISMATCH"
DOCUMENT_REGISTRATION_ID_MISMATCH = "DOCUMENT_REGISTRATION_ID_MISMATCH"
DOCUMENT_INPUT_BINDING_MISMATCH = "DOCUMENT_INPUT_BINDING_MISMATCH"
DOCUMENT_SOURCE_ARTIFACT_MISSING = "DOCUMENT_SOURCE_ARTIFACT_MISSING"
DOCUMENT_SOURCE_INTEGRITY_FAILED = "DOCUMENT_SOURCE_INTEGRITY_FAILED"
DOCUMENT_SOURCE_RECEIPT_MISSING = "DOCUMENT_SOURCE_RECEIPT_MISSING"
DOCUMENT_SOURCE_EFFECT_UNRESOLVED = "DOCUMENT_SOURCE_EFFECT_UNRESOLVED"
DOCUMENT_MEDIA_TYPE_MISMATCH = "DOCUMENT_MEDIA_TYPE_MISMATCH"
DOCUMENT_AUTHORIZATION_FAILED = "DOCUMENT_AUTHORIZATION_FAILED"
DOCUMENT_STALE_FENCING_TOKEN = "DOCUMENT_STALE_FENCING_TOKEN"
DOCUMENT_IDEMPOTENCY_CONFLICT = "DOCUMENT_IDEMPOTENCY_CONFLICT"
DOCUMENT_LINEAGE_UNKNOWN = "DOCUMENT_LINEAGE_UNKNOWN"
DOCUMENT_LINEAGE_SCOPE_MISMATCH = "DOCUMENT_LINEAGE_SCOPE_MISMATCH"
DOCUMENT_LINEAGE_CYCLE = "DOCUMENT_LINEAGE_CYCLE"
DOCUMENT_IMMUTABLE_HISTORY_MUTATION = "DOCUMENT_IMMUTABLE_HISTORY_MUTATION"
DOCUMENT_ARTIFACT_RECEIPT_MISMATCH = "DOCUMENT_ARTIFACT_RECEIPT_MISMATCH"
DOCUMENT_LEDGER_EVENT_MISMATCH = "DOCUMENT_LEDGER_EVENT_MISMATCH"
DOCUMENT_CAS_CONFLICT = "DOCUMENT_CAS_CONFLICT"
DOCUMENT_EFFECT_RECEIPT_MISSING = "DOCUMENT_EFFECT_RECEIPT_MISSING"
DOCUMENT_REGISTRATION_INCOMPLETE = "DOCUMENT_REGISTRATION_INCOMPLETE"
DOCUMENT_RECONCILIATION_REQUIRED = "DOCUMENT_RECONCILIATION_REQUIRED"
LEGACY_DOCUMENT_REGISTRATION_EVIDENCE_REQUIRED = (
    "LEGACY_DOCUMENT_REGISTRATION_EVIDENCE_REQUIRED"
)


class DocumentRegistryError(RuntimeError):
    """A typed K01 refusal whose code is stable across adapters."""

    def __init__(
        self,
        code: str,
        detail: str,
        metadata: Mapping[str, Any] | None = None,
    ) -> None:
        self.code = code
        self.detail = detail
        self.metadata = dict(metadata or {})
        super().__init__(f"{code}: {detail}")


def fail(
    code: str,
    detail: str,
    metadata: Mapping[str, Any] | None = None,
) -> NoReturn:
    """Raise one typed registry error without a permissive fallback."""
    raise DocumentRegistryError(code, detail, metadata)

__all__ = [
    name
    for name in globals()
    if name.startswith("DOCUMENT_")
    or name == "LEGACY_DOCUMENT_REGISTRATION_EVIDENCE_REQUIRED"
    or name in {"DocumentRegistryError", "fail"}
]
