"""Pinned parser-output adapters and visible fallback/disagreement records (K02)."""

from .adapters import (
    PARSER_ADAPTER_VERSION,
    ArtifactEnvelope,
    ElementKind,
    ElementObservation,
    FallbackDisposition,
    FallbackResolution,
    ParserAttempt,
    ParserContractError,
    ParserPin,
    ParserRole,
    ParserStatus,
    ParserStream,
    ReconciliationComparison,
    adapt_docling_artifact,
    adapt_fallback_artifact,
    adapt_grobid_artifact,
    blocked_attempt,
    compare_parser_streams,
    resolve_fallback,
)

__all__ = [
    "PARSER_ADAPTER_VERSION",
    "ArtifactEnvelope",
    "ElementKind",
    "ElementObservation",
    "FallbackDisposition",
    "FallbackResolution",
    "ParserAttempt",
    "ParserContractError",
    "ParserPin",
    "ParserRole",
    "ParserStatus",
    "ParserStream",
    "ReconciliationComparison",
    "adapt_docling_artifact",
    "adapt_fallback_artifact",
    "adapt_grobid_artifact",
    "blocked_attempt",
    "compare_parser_streams",
    "resolve_fallback",
]
