"""Evolution evidence retrieval, layered novelty and coverage-debt acquisition.

Every record here is declared inside a pinned K05 corpus snapshot and its
prior-art boundary; the lane vocabulary, lane order, receipt states, plan
dispositions and novelty layers are read from the canonical schemas that
declare them.  Nothing here scores, promotes, or reads a clock.
"""

from __future__ import annotations

from .acquisition import (
    ACQUISITION_ID_PREFIX,
    ADVERSARIAL_LANE_POSITIONS,
    CERTIFICATE_SCHEMA,
    EXECUTION_KIND_POSITION,
    EXHAUSTED_STOP_POSITION,
    EXTERNAL_LANE_POSITION,
    EXTERNAL_LAYER_POSITION,
    FINDING_CODES,
    LAYERED_ID_PREFIX,
    NICHE_SCHEMA,
    PLAN_ID_PREFIX,
    RECEIPT_ID_PREFIX,
    RECEIPT_SCHEMA,
    SEARCHED_NONE_STATE_POSITION,
    SEARCHED_WITH_RESULTS_STATE_POSITION,
    SELECTED_DISPOSITION_POSITION,
    SENTINEL_KIND_POSITION,
    TARGET_ID_PREFIX,
    UNSEARCHED_STATE_POSITION,
    VECTOR_ID_PREFIX,
    VECTOR_SCHEMA,
    AcquisitionError,
    acquisition_plan_is_rederivable,
    adversarial_lanes,
    assess_layered_novelty,
    build_coverage_debt_acquisition_plan,
    build_evolution_retrieval_plan,
    canonical_lane_order,
    canonical_layer_scores,
    coverage_state,
    emit_searched_lane_receipt,
    emit_unsearched_lane_receipt,
    external_novelty_lane,
    lane_vocabulary,
    novelty_layer_vocabulary,
    plan_disposition_vocabulary,
    rank_acquisition_targets,
    receipt_kind_vocabulary,
    receipt_state_vocabulary,
    require_acquisition_plan_identity,
    require_layered_novelty_identity,
    require_plan_identity,
    sentinel_reason_vocabulary,
    statement_digest,
    stop_reason_vocabulary,
)

__all__ = [
    "ACQUISITION_ID_PREFIX",
    "ADVERSARIAL_LANE_POSITIONS",
    "CERTIFICATE_SCHEMA",
    "EXECUTION_KIND_POSITION",
    "EXHAUSTED_STOP_POSITION",
    "EXTERNAL_LANE_POSITION",
    "EXTERNAL_LAYER_POSITION",
    "FINDING_CODES",
    "LAYERED_ID_PREFIX",
    "NICHE_SCHEMA",
    "PLAN_ID_PREFIX",
    "RECEIPT_ID_PREFIX",
    "RECEIPT_SCHEMA",
    "SEARCHED_NONE_STATE_POSITION",
    "SEARCHED_WITH_RESULTS_STATE_POSITION",
    "SELECTED_DISPOSITION_POSITION",
    "SENTINEL_KIND_POSITION",
    "TARGET_ID_PREFIX",
    "UNSEARCHED_STATE_POSITION",
    "VECTOR_ID_PREFIX",
    "VECTOR_SCHEMA",
    "AcquisitionError",
    "acquisition_plan_is_rederivable",
    "adversarial_lanes",
    "assess_layered_novelty",
    "build_coverage_debt_acquisition_plan",
    "build_evolution_retrieval_plan",
    "canonical_lane_order",
    "canonical_layer_scores",
    "coverage_state",
    "emit_searched_lane_receipt",
    "emit_unsearched_lane_receipt",
    "external_novelty_lane",
    "lane_vocabulary",
    "novelty_layer_vocabulary",
    "plan_disposition_vocabulary",
    "rank_acquisition_targets",
    "receipt_kind_vocabulary",
    "receipt_state_vocabulary",
    "require_acquisition_plan_identity",
    "require_layered_novelty_identity",
    "require_plan_identity",
    "sentinel_reason_vocabulary",
    "statement_digest",
    "stop_reason_vocabulary",
]
