"""Public I03 ontology and measurement-resolution component API."""

from .resolver import (
    ONTOLOGY_RESOLVER_VERSION,
    CandidateAssessment,
    CompatibilityStatus,
    ConstructEquivalence,
    ContextConstraints,
    MappingContext,
    MappingImpact,
    MappingReviewItem,
    MeasurementBridge,
    MeasurementCompatibility,
    MeasurementIdentity,
    OntologyContractError,
    OntologyEntry,
    OntologyEntityKind,
    OntologyResolution,
    PromotionCeiling,
    ResolutionPolicy,
    ResolutionStatus,
    compare_measurements,
    resolve_construct,
)

__all__ = [
    "ONTOLOGY_RESOLVER_VERSION",
    "CandidateAssessment",
    "CompatibilityStatus",
    "ConstructEquivalence",
    "ContextConstraints",
    "MappingContext",
    "MappingImpact",
    "MappingReviewItem",
    "MeasurementBridge",
    "MeasurementCompatibility",
    "MeasurementIdentity",
    "OntologyContractError",
    "OntologyEntry",
    "OntologyEntityKind",
    "OntologyResolution",
    "PromotionCeiling",
    "ResolutionPolicy",
    "ResolutionStatus",
    "compare_measurements",
    "resolve_construct",
]
